name: CI/CD to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Backend Dependencies
        working-directory: backend
        run: npm install --legacy-peer-deps
      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm install --legacy-peer-deps
      - name: Install Admin Dependencies
        working-directory: admin
        run: npm install --legacy-peer-deps
      # - name: Load environment variables for backend
      #   run: |
      #     cd backend
      #     echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" >> .env
      #     echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
      #     echo "PORT=${{ secrets.PORT }}" >> .env
      #     echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
      #     echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
      #     echo "FACEBOOK_CLIENT_ID=${{ secrets.FACEBOOK_CLIENT_ID }}" >> .env
      #     echo "FACEBOOK_CLIENT_SECRET=${{ secrets.FACEBOOK_CLIENT_SECRET }}" >> .env
      #     echo "EMAIL_USER=${{ secrets.EMAIL_USER }}" >> .env
      #     echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> .env
      # - name: Load environment variables for frontend
      #   run: |
      #     cd frontend
      #     echo "NEXT_PUBLIC_BACKEND_URL=${{ secrets.NEXT_PUBLIC_BACKEND_URL }}" >> .env
      #     echo "NEXT_PUBLIC_FRONTEND_URL=${{ secrets.NEXT_PUBLIC_FRONTEND_URL }}" >> .env
      #     echo "NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}" >> .env
      #     echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> .env
      #     echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> .env
      #     echo "FACEBOOK_CLIENT_ID=${{ secrets.FACEBOOK_CLIENT_ID }}" >> .env
      #     echo "FACEBOOK_CLIENT_SECRET=${{ secrets.FACEBOOK_CLIENT_SECRET }}" >> .env

      # - name: Load environment variables for admin
      #   run: |
      #     cd admin
      #     echo "REACT_APP_BACKEND_URL=${{ secrets.REACT_APP_BACKEND_URL }}" >> .env

      - name: Dotenv Action for frontend
        uses: falti/dotenv-action@v0.2.4
        with:
          path: "./frontend/.env"
      - name: Build Frontend
        run: npm run build --prefix frontend

      # - name: Dotenv Action for backend
      #   uses: falti/dotenv-action@v0.2.4
      #   with:
      #     path: "./backend/.env"
      # - name: Build Backend
      #   run: npm start --prefix backend

      - name: Dotenv Action for admin
        uses: falti/dotenv-action@v0.2.4
        with:
          path: "./admin/.env"
      - name: Build Admin
        run: npm run build --prefix admin

      - name: Deploy to DigitalOcean
        run: |
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.DROPLET_IP }} << EOF
          cd /path/to/your/application
          git pull origin main
          npm install
          npm run build
          pm2 restart app
          EOF
